services:
  d4lia_db_service:
    image: postgres:17
    container_name: d4lia_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    command: >
      postgres -c max_connections=500
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - d4lia_db_data:/var/lib/postgresql/data
    networks:
      - d4lia_network

  d4lia_redis:
    image: redis:7
    container_name: d4lia_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - d4lia_network
    volumes:
      - d4lia_redis_data:/data

  d4lia_celery_worker:
    build: .
    container_name: d4lia_celery_worker
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - d4lia_redis
    environment:
      - CELERY_BROKER_URL=redis://d4lia_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://d4lia_redis:6379/1
    networks:
      - d4lia_network
    volumes:
      - .:/app
    working_dir: /app

  d4lia_celery_flower:
    build: .
    container_name: d4lia_celery_flower
    command: celery -A app.celery_app flower --port=5555 --loglevel=info
    depends_on:
      - d4lia_redis
    ports:
      - "7000:5555"
    environment:
      - CELERY_BROKER_URL=redis://d4lia_redis:6379/0
    networks:
      - d4lia_network
    volumes:
      - .:/app
    working_dir: /app

networks:
  d4lia_network:
    driver: bridge

volumes:
  d4lia_db_data:
  d4lia_redis_data:
